<?php
/**
 * 适用于登录场景
 * Created by PhpStorm.
 * User: Lint
 * Date: 2020/9/24
 * Time: 16:37
 */

namespace app\api\controller;

use app\BaseController;
use app\common\business\Sms as SmsBus;
use app\api\validate\User as UserValidate;
use app\common\business\User;

class AuthBase extends ApiBase
{
    public $accessToken = '';
    public $userId = 0;
    public $username = '';

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->accessToken = $this->request->header('access-token');
        // $this->isLogin();
        if (!$this->accessToken || !$this->isLogin()) {
            return $this->show(config('status.not_login'), '请先登录');
        }
    }

    /**
     * Notess:判断是否登录
     * User: Lint
     * Date: 2020/9/27 19:34
     * @return bool
     */
    public function isLogin()
    {
        $userInfo = cache(config('redis.token_pre') . $this->accessToken);
        if (!$userInfo) {
            return false;
        }
        if (!empty($userInfo['id']) && !empty($userInfo['username'])) {
            $this->userId = $userInfo['id'];
            $this->username = $userInfo['username'];
            return true;
        }
        return false;
    }
}
