<?php
/**
 * 适用于非登录场景
 * Created by PhpStorm.
 * User: Lint
 * Date: 2020/9/24
 * Time: 16:37
 */

namespace app\api\controller;

use app\BaseController;
use app\common\business\Sms as SmsBus;
use app\api\validate\User as UserValidate;
use app\common\business\User;
use think\exception\HttpResponseException;

class ApiBase extends BaseController
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function show(...$args)
    {
        // dump(...$args);
        throw new HttpResponseException(show(...$args));
    }
}
